spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fretcorridor
  client:
    service-exe:
      base-url: http://service-exe:8093
      connect-timeout-ms: 500
      read-timeout-ms: 1000
